//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated.
//
//    Manual changes to this file may cause unexpected behavior in your application.  
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

const SourceWebAppTest = {
    'Home':{
        'Index':()=>_getUrl("Home","Index"),
    },
    'User':{
        'Index':()=>_getUrl("User","Index"),
        'Create':()=>_getUrl("User","Create"),
        'Delete':()=>_getUrl("User","Delete"),
    },
}