//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated.
//
//    Manual changes to this file may cause unexpected behavior in your application.  
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

const SourceWebAppTest = {
    'HomeController':{
        'Index':()=>_getUrl("HomeController","Index"),
    },
    'UserController':{
        'Index':()=>_getUrl("UserController","Index"),
        'Create':()=>_getUrl("UserController","Create"),
        'Delete':()=>_getUrl("UserController","Delete"),
    },
}